<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.1.0 http://maven.apache.org/xsd/maven-4.1.0.xsd">
	<modelVersion>4.1.0</modelVersion>

	<parent>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<artifactId>rocksdbffm-bom</artifactId>
	<name>RocksDB FFM BOM</name>
	<packaging>bom</packaging>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>io.github.dfa1</groupId>
				<artifactId>rocksdbffm-core</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>io.github.dfa1</groupId>
				<artifactId>rocksdbffm-tool-ldb</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>io.github.dfa1</groupId>
				<artifactId>rocksdbffm-tool-sstdump</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>io.github.dfa1</groupId>
				<artifactId>rocksdbffm-native-osx-aarch64</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>io.github.dfa1</groupId>
				<artifactId>rocksdbffm-native-linux-x86_64</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>io.github.dfa1</groupId>
				<artifactId>rocksdbffm-native-linux-aarch64</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>io.github.dfa1</groupId>
				<artifactId>rocksdbffm-native-windows-x86_64</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>io.github.dfa1</groupId>
				<artifactId>rocksdbffm-native-windows-aarch64</artifactId>
				<version>${project.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

</project>
